### ISSUE TITLE
BBB-Moodle upgedated

### ISSUE THREAD

**Issue by michael-schneider** [bash/bbb-moodle-prettifier#1]
Das BBB-Moodle ist upgedated auf die neuste Version und das Design hat gewechselt: Von Genesis auf [lambda](http://themeforest.net/item/lambda-responsive-moodle-theme/9442816?s_rank=1).

**Comment by bash** [comment]
The new version should be available for download from the chrome webstore in a few hours.
https://chrome.google.com/webstore/detail/bbb-moodle-prettifier/fbnoacnkmdhnmghankinjgbmlinjpkhg
